"use client";
import { LoginAuth } from "../../../actions/loginAuth";
import {
  updateUser,
  registerUser,
  getData,
  get7daysData,
  get7daysDataFromAll,
  getLiveData,
} from "../../DB/dbFunctions";

export default function Test() {
  // const data = {
  //   live: {
  //     tables: [
  //       {
  //         tableNumber: "T1",
  //         capacity: 4,
  //         status: "available",
  //         customer: null,
  //         issuesReported: {},
  //       },
  //       {
  //         tableNumber: "T2",
  //         capacity: 2,
  //         status: "occupied",
  //         customer: {
  //           name: "Alice Smith",
  //           email: "alice@example.com",
  //           phone: "123-456-7890",
  //           diningDetails: {
  //             timeSeated: JSON.stringify(new Date("2024-09-23T18:30:00Z")),
  //             orders: [
  //               {
  //                 itemId: "67890",
  //                 itemName: "Spaghetti Carbonara",
  //                 portionSize: "Large",
  //                 price: 25,
  //               },
  //               {
  //                 itemId: "67891",
  //                 itemName: "Garlic Bread",
  //                 portionSize: "Small",
  //                 price: 5,
  //               },
  //             ],
  //             payment: {
  //               mode: "online",
  //               paymentId: "TXN67890",
  //               timeOfTransaction: JSON.stringify(
  //                 new Date().toLocaleTimeString()
  //               ),
  //               price: 35,
  //               priceAfterDiscount: 30,
  //               discount: {
  //                 type: "coupon",
  //                 amount: 3,
  //                 code: "SAVE10",
  //               },
  //             },
  //             attendant: "Bob Johnson",
  //           },
  //         },
  //         issuesReported: {
  //           lateService: {
  //             category: "service",
  //             name: "Late order delivery",
  //             description: "Spaghetti Carbonara took too long to arrive.",
  //             reportTime: JSON.stringify(new Date("2024-09-23T19:00:00Z")),
  //             status: "Assigned",
  //             attendant: "Charlie Brown",
  //             resolutionTime: null,
  //           },
  //         },
  //       },
  //     ],
  //   },
  // };

  let usr;
  const handleUser = async () => {
    const user = await registerUser("surajnimeshh1000@gmail.com", data);
    console.log(user);
  };

  return (
    <div>
      <h1>{JSON.stringify(usr)}</h1>
      <button onClick={() => handleUser()}>Click</button>
    </div>
  );
}

//  const data = {
//    rooms: {
//      categories: {
//        executive: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 7,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 70000,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 68000,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 66000,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 7,
//              avgPriceOfFood: 0,
//              totalEarnings: 58000,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              totalEarnings: 63000,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 67000,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 7,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 7,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 62000,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 7,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Executive",
//        },
//        deluxe: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 7,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 7,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 81000,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 79000,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 77000,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 7,
//              avgPriceOfFood: 0,
//              totalEarnings: 65000,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              totalEarnings: 74000,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 73000,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 7,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 7,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 71000,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 7,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Deluxe",
//        },
//        suite: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 7,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 7,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 137000,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 135000,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 133000,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 7,
//              avgPriceOfFood: 0,
//              totalEarnings: 130000,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              totalEarnings: 129000,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 81000,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 7,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 127000,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 127000,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 7,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Suite",
//        },
//        "super suite": {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 7,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 7,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 66000,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 64000,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 62000,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 7,
//              avgPriceOfFood: 0,
//              totalEarnings: 59000,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 7,
//              totalEarnings: 60000,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 57000,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 7,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 7,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 56000,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 7,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Super Suite",
//        },
//      },
//    },
//    food: {
//      categories: {
//        "in-house restaurant": {
//          weeks: {
//            38: {
//              totalEarnings: 0,
//              avgDiningDuration: 0,
//              totalBookings: 0,
//              totalIssues: 0,
//              avgPricPerOrder: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPrice: 0,
//              totalIssues: 0,
//              avgPricPerOrder: 0,
//              totalBookings: 10,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgDiningDuration: 0,
//              totalEarnings: 41000,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              totalBookings: 10,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgDiningDuration: 0,
//              totalEarnings: 39000,
//              avgPricPerOrder: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              avgDiningDuration: 0,
//              totalBookings: 10,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPricPerOrder: 0,
//              totalEarnings: 37000,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//            },
//            265: {
//              avgPrice: 0,
//              totalIssues: 0,
//              avgPricPerOrder: 0,
//              totalBookings: 10,
//              avgPriceOfFood: 0,
//              totalEarnings: 35000,
//              avgDiningDuration: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//            },
//            264: {
//              avgDiningDuration: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalBookings: 10,
//              totalEarnings: 33000,
//              avgPriceOfFood: 0,
//              avgPricPerOrder: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgDiningDuration: 0,
//              avgPricPerOrder: 0,
//              totalEarnings: 32000,
//              totalBookings: 10,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPricPerOrder: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 10,
//              avgDiningDuration: 0,
//              totalEarnings: 30000,
//            },
//          },
//          months: {
//            9: {
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarnings: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgDiningDuration: 0,
//              totalBookings: 10,
//              avgPricPerOrder: 0,
//            },
//          },
//          name: "In-house Restaurant",
//        },
//        restaurant: {
//          weeks: {
//            38: {
//              totalEarnings: 0,
//              avgDiningDuration: 0,
//              totalBookings: 10,
//              totalIssues: 0,
//              avgPricPerOrder: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPrice: 0,
//              totalIssues: 0,
//              avgPricPerOrder: 0,
//              totalBookings: 10,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgDiningDuration: 0,
//              totalEarnings: 51000,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              totalBookings: 10,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgDiningDuration: 0,
//              totalEarnings: 49000,
//              avgPricPerOrder: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              avgDiningDuration: 0,
//              totalBookings: 10,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPricPerOrder: 0,
//              totalEarnings: 47000,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//            },
//            265: {
//              avgPrice: 0,
//              totalIssues: 0,
//              avgPricPerOrder: 0,
//              totalBookings: 10,
//              avgPriceOfFood: 0,
//              totalEarnings: 43000,
//              avgDiningDuration: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//            },
//            264: {
//              avgDiningDuration: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalBookings: 10,
//              totalEarnings: 45000,
//              avgPriceOfFood: 0,
//              avgPricPerOrder: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgDiningDuration: 0,
//              avgPricPerOrder: 0,
//              totalEarnings: 41000,
//              totalBookings: 10,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPricPerOrder: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 10,
//              avgDiningDuration: 0,
//              totalEarnings: 40000,
//            },
//          },
//          months: {
//            9: {
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarnings: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalOrdersOnline: 0,
//              totalOrdersForDelivery: 0,
//              totalOrdersForTakeaway: 0,
//              avgPriceForOrdersOnline: 0,
//              avgPriceForOrdersDelivery: 0,
//              avgPriceForOrdersTakeaway: 0,
//              avgDiningDuration: 0,
//              totalBookings: 0,
//              avgPricPerOrder: 0,
//            },
//          },
//          name: "Restaurant",
//        },
//      },
//    },
//    services: {
//      categories: {
//        spa: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 5,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 31000,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 29000,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 27000,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 5,
//              avgPriceOfFood: 0,
//              totalEarnings: 25000,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              totalEarnings: 23000,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 27000,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 5,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 5,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 31000,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 5,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Spa",
//        },
//        gym: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 5,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 5,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 26200,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 24000,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 22000,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 5,
//              avgPriceOfFood: 0,
//              totalEarnings: 20000,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              totalEarnings: 18000,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 21000,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 5,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 5,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 15000,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 5,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Gym",
//        },
//        laundry: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 5,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 5,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 21000,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 19000,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 17000,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 5,
//              avgPriceOfFood: 0,
//              totalEarnings: 15000,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              totalEarnings: 13000,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 11000,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 5,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 5,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 14000,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 5,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Laundry",
//        },
//        pool: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 5,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 5,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 36000,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 34000,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 32000,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 5,
//              avgPriceOfFood: 0,
//              totalEarnings: 30000,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 5,
//              totalEarnings: 28000,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 26200,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 5,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 5,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 25000,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 0,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Pool",
//        },
//      },
//    },
//    issues: {
//      categories: {
//        rooms: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 2,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 32,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 2,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 25,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 2,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 62,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 2,
//              avgPriceOfFood: 0,
//              totalEarnings: 46,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 2,
//              totalEarnings: 22,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 15,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 2,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 2,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 23,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 2,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Rooms",
//        },
//        Food: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 2,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 2,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 14,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 2,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 11,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 2,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 13,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 2,
//              avgPriceOfFood: 0,
//              totalEarnings: 15,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 2,
//              totalEarnings: 19,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 12,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 2,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 2,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 16,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 2,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Food",
//        },
//        services: {
//          weeks: {
//            38: {
//              avgPriceOfServices: 0,
//              totalEarnings: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 2,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromServices: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//            },
//          },
//          days: {
//            268: {
//              avgPriceOfServices: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalBookings: 2,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 8,
//              totalServiceRequests: 0,
//              avgPriceOfFood: 0,
//            },
//            267: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 2,
//              totalFoodOrders: 0,
//              avgStayDuration: 0,
//              totalEarnings: 5,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//            },
//            266: {
//              totalEarningsFromServices: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 2,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfRooms: 0,
//              totalEarnings: 7,
//              totalFoodOrders: 0,
//            },
//            265: {
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarningsFromServices: 0,
//              avgPriceOfRooms: 0,
//              totalBookings: 2,
//              avgPriceOfFood: 0,
//              totalEarnings: 1,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//            },
//            264: {
//              totalServiceRequests: 0,
//              avgPriceOfMinibar: 0,
//              avgStayDuration: 0,
//              totalFoodOrders: 0,
//              totalIssues: 0,
//              totalEarningsFromMinibar: 0,
//              avgPrice: 0,
//              avgPriceOfServices: 0,
//              totalBookings: 2,
//              totalEarnings: 9,
//              totalEarningsFromServices: 0,
//              avgPriceOfFood: 0,
//              avgPriceOfRooms: 0,
//            },
//            263: {
//              avgPriceOfFood: 0,
//              avgStayDuration: 0,
//              avgPriceOfServices: 0,
//              avgPriceOfRooms: 0,
//              avgPriceOfMinibar: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 4,
//              totalServiceRequests: 0,
//              totalEarningsFromMinibar: 0,
//              totalBookings: 2,
//              totalIssues: 12,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//            },
//            262: {
//              avgPriceOfRooms: 0,
//              totalIssues: 0,
//              totalFoodOrders: 0,
//              avgPrice: 0,
//              avgPriceOfFood: 0,
//              totalBookings: 2,
//              totalEarningsFromServices: 0,
//              avgPriceOfMinibar: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalEarningsFromMinibar: 0,
//              totalEarnings: 5,
//              avgPriceOfServices: 0,
//            },
//          },
//          months: {
//            9: {
//              avgPriceOfServices: 0,
//              avgPriceOfMinibar: 0,
//              totalIssues: 0,
//              avgPrice: 0,
//              totalEarningsFromServices: 0,
//              totalEarnings: 0,
//              totalEarningsFromMinibar: 0,
//              avgPriceOfFood: 0,
//              totalFoodOrders: 0,
//              totalServiceRequests: 0,
//              avgStayDuration: 0,
//              totalBookings: 0,
//              avgPriceOfRooms: 0,
//            },
//          },
//          name: "Services",
//        },
//      },
//    },
//  };

// const hotellive = {
//   live: {
//     rooms: [
//       {
//         roomNumber: "101",
//         bookingId: "RO:8966",
//         status: "reserved",
//         attendent: "Shyam Mishra",
//         payment: {
//           mode: "online",
//           paymentId: "TXN123456",
//           timeOfTransaction: JSON.stringify(new Date().toLocaleTimeString()),
//           price: 30,
//           priceAfterDiscount: 27,
//           discount: {
//             type: "coupon",
//             amount: 3,
//             code: "SAVE10",
//           },
//         },
//         customer: {
//           name: "John Doe",
//           email: "johndoe@example.com",
//           phone: "123-456-7890",
//           checkIn: JSON.stringify(new Date("2024-09-20T15:00:00Z")),
//           checkOut: JSON.stringify(new Date("2024-09-25T11:00:00Z")),
//           noOfGuests: 2,
//           specialRequirements: "Require a hypoallergenic pillow.",
//         },
//         diningDetails: {
//           orders: [
//             {
//               orderId: "OR:123",
//               items: [
//                 {
//                   itemName: "Pizza",
//                   portionSize: "Large",
//                   price: 20,
//                 },
//                 {
//                   itemName: "Salad",
//                   portionSize: "Small",
//                   price: 10,
//                 },
//               ],
//               attendant: "Alice Smith",
//               status: "open",
//               payment: {
//                 mode: "online",
//                 paymentId: "TXN123456",
//                 timeOfTransaction: JSON.stringify(
//                   new Date().toLocaleTimeString()
//                 ),
//                 price: 30,
//                 priceAfterDiscount: 27,
//                 discount: {
//                   type: "coupon",
//                   amount: 3,
//                   code: "SAVE10",
//                 },
//               },
//             },
//           ],
//         },
//         servicesUsed: {
//           massage: {
//             serviceId: "SE:123",
//             serviceName: "Massage",
//             type: "massage",
//             requestTime: JSON.stringify(new Date().toLocaleTimeString()),
//             startTime: JSON.stringify(new Date().toLocaleTimeString()),
//             endTime: JSON.stringify(new Date().toLocaleTimeString()),
//             price: 50,
//             attendant: "Bob Johnson",
//             payment: {
//               mode: "offline",
//               paymentId: "CASH123",
//               timeOfTransaction: JSON.stringify(
//                 new Date().toLocaleTimeString()
//               ),
//               price: 60,
//               priceAfterDiscount: 50,
//               discount: {
//                 type: "coupon",
//                 amount: 3,
//                 code: "SAVE10",
//               },
//             },
//           },
//         },
//         issuesReported: {
//           maintenance: {
//             issueId: "IS:123",
//             category: "maintenance",
//             name: "Leaking faucet",
//             description: "Faucet in the bathroom is leaking.",
//             reportTime: JSON.stringify(new Date("2024-09-21T18:00:00Z")),
//             status: "Assigned",
//             attendant: "Charlie Brown",
//             resolutionTime: null,
//           },
//         },
//       },
//       // Add more rooms here
//     ],
//   },
// };
